name: byte_message
description: "Inter-chip 协议编码/解码的纯 Dart 库：提供数据包模型、常量、工具方法、编码器与解码器，支持 |Flag|Len|LenH|Cmd|Payload|Checksum| 格式。"
version: 1.2.0
homepage: https://gitee.com/quantsai/byte-message.git
repository: 'https://gitee.com/quantsai/byte-message.git'
issue_tracker: https://gitee.com/quantsai/byte-message/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

  

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.15

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
topics:
  - byte-message
  - protocol
  - inter-chip

